---
- name: add_user_to_docker_group
  become: true
  user:
      name: ta28ma2
      groups: docker
      append: yes

- name: restart_docker_daemon
  become: true
  service:
      name: docker
      state: restarted
